### ISSUE TITLE
Inconsistent type for classifications.currentAnnotations

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1325]
**Package**
lib-classifier

**Describe the bug**
https://github.com/zooniverse/front-end-monorepo/blob/1853e992f0f771efdee82c274fc42a97679627db/packages/lib-classifier/src/store/ClassificationStore.js#L24-L30
`classifications.currentAnnotations` (note the 's'!) returns a map of annotations or an array by default. Code that uses `currentAnnotations` must also check its type before performing operations on it, such as `classifications.currentAnnotations.get(taskKey)`.

Found while working on #1319.

**To Reproduce**

**Expected behavior**
`classifications.currentAnnotations` should either convert the annotations map to an array or return an empty map by default.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by srallen** [comment]
Wouldn't this be resolved by #1226?

**Comment by goplayoutside3** [comment]
@eatyourgreens by reading this Issue I'm unsure of how to reproduce the bug. Is this still an issue in the classifier?

**Comment by eatyourgreens** [comment]
The broken code is still present on the main branch:
https://github.com/zooniverse/front-end-monorepo/blob/bc615471898d3a5257da8ffa0ac7c5c40ec9640e/packages/lib-classifier/src/store/ClassificationStore.js#L30-L36

Reproduction seems reasonably straightforward. This code snippet will fail if `classifications.currentAnnotations` is an array (not a map):

```js
store.classifications.currentAnnotations.get(annotationID)
```

**Comment by goplayoutside3** [comment]
In what specific cases and/or Zooniverse projects would `classifications.currentAnnotations` be an array (not a map)?

**Comment by eatyourgreens** [comment]
When line 35 runs and returns an empty array.

**Comment by eatyourgreens** [comment]
Either line 33 should be returning an array, not a map, or line 35 should be returning a map, not an array. It's not clear to me whether `classifications.currentAnnotations` is expected to be a map or an array.

**Comment by goplayoutside3** [comment]
Okay thanks! Will continue to investigate
