### ISSUE TITLE
Project app: slow build times on dynamic Classify pages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2741]
## Package
app-project

## Describe the bug
Project Classify pages can take 1s or more to build on projects with workflow selection or subject set selection.

## To Reproduce
On a project like HMS NHS or Davy Notebooks, go to Classify and wait for the workflow choices to load. The lag can be quite noticeable.
https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service
https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/

## Expected behavior
Page props are only ~12k for HMS NHS, so I'd expect download times under 100ms.

## Additional context
Static builds (#2531) will fix this by serving static page HTML and JSON from the CDN cache. I'd still like to investigate why `getServerSideProps` is taking so long to run. It could be that there are redundant network calls being run for each page request, which we can remove.

**Comment by lcjohnso** [comment]
Fixed by #2531

**Comment by eatyourgreens** [comment]
#2531 didn’t fix the page builds. `getStaticProps` can still take ~1s to execute. #2531 cached the page props so that they aren’t calculated on every request.
